version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.10.0

    steps:
      - checkout

      - run:
          name: Ruby deps # ugh
          command: |
            apt-get update && apt-get install ruby-sass
            gem install compass --no-ri --no-rdoc

      - restore_cache:
          key: grunt-and-bower
      - run:
          name: Install grunt and bower
          command: yarn global add bower grunt-cli
      - save_cache:
          key: grunt-and-bower
          paths:
            - ~/.config/yarn/global

      - restore_cache:
          key: bower-deps-{{ checksum "bower.json" }}
      - run:
          name: Install bower deps
          command: ~/.config/yarn/global/node_modules/.bin/bower i
      - save_cache:
          key: bower-deps-{{ checksum "bower.json" }}
          paths:
            - bower_components

      - restore_cache:
          key: node-deps-{{ checksum "yarn.lock" }}
      - run:
          name: Node dependencies
          command: yarn --pure-lockfile
      - save_cache:
          key: node-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  test:
    docker:
      - image: circleci/node:8.10.0-browsers
        environment:
          JOBS: 2

    steps:
      - checkout
      - restore_cache:
          key: bower-deps-{{ checksum "bower.json" }}
      - restore_cache:
          key: node-deps-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: modernizr-{{ .Revision }}
      - run:
          name: Test
          command: ./node_modules/ember-cli/bin/ember test

  deploy:
    docker:
      - image: circleci/node:8.10.0
        environment:
          JOBS: 2
    steps:
      - checkout
      - restore_cache:
          key: bower-deps-{{ checksum "bower.json" }}
      - restore_cache:
          key: node-deps-{{ checksum "yarn.lock" }}
      - run:
          name: Deploy to S3
          command: |
            env | sed -n 's/^DEPLOY_//p' > .env
            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              env | sed -n 's/^DEMO_//p' >> .env
              ./node_modules/ember-cli/bin/ember deploy demo --verbose --activate
            elif grep -q "v[0-9]\+\.[0-9]\+\.[0-9]\+" <<< "$CIRCLE_TAG"; then
              env | sed -n 's/^PROD_//p' >> .env
              ./node_modules/ember-cli/bin/ember deploy production --verbose --activate
            fi

workflows:
  version: 2
  just-build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              only: master
